name: Test and build examples

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: apt-get update && apt-get install -y build-essential
    - name: build
      run: make install
    - name: build examples
      run: make clean_examples && make examples
