name: Test and build examples

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get gendev
      run: wget https://github.com/kubilus1/gendev/releases/download/0.4.1/gendev_0.4.1_all.deb 
    - name: Install gendev
      run: sudo apt-get install -y ./gendev_0.4.1_all.deb
    - name: build
      run: make install
    - name: build examples
      run: make clean_examples && make examples
